In [1]:
from DemoServerDBTWO import ConnectDatabase

In [2]:
temp = ConnectDatabase()

In [3]:
temp.cur.execute('SELECT * from transaction_master')

In [4]:
trans_master = temp.cur.fetchall()

In [5]:
trans_master[0]

('536365',
 '85123A',
 'WHITE HANGING HEART T-LIGHT HOLDER',
 6,
 2.55,
 17850,
 'United Kingdom',
 15.3,
 datetime.date(2010, 12, 1))

In [6]:
col_names = [desc[0] for desc in temp.cur.description]

In [7]:
import yaml
with open('/home/ubuntu/MappingBuffer2.yml', 'r') as f:
    doc = yaml.load(f)

In [8]:
doc['column_map']['TRANSACTION_MASTER']['product_id']

'prod_id'

In [9]:
import pandas as pd
import numpy as np

In [10]:
trans_df = pd.DataFrame(trans_master)

In [11]:
trans_df.columns = col_names

In [12]:
trans_df.rename(columns={doc['column_map']['TRANSACTION_MASTER']['cust_id']:'cust_id'}, inplace = True)
trans_df.rename(columns={doc['column_map']['TRANSACTION_MASTER']['revenue']:'revenue'}, inplace = True)
trans_df.rename(columns={doc['column_map']['TRANSACTION_MASTER']['product_id']:'product_id'}, inplace = True)
trans_df.rename(columns={doc['column_map']['TRANSACTION_MASTER']['timestamp']:'timestamp'}, inplace = True)

In [13]:
trans_df.head(6)

,InvoiceNo,product_id,prod_desc,quantity,unitprice,cust_id,country,revenue,timestamp
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850,United Kingdom,15.30,2010-12-01
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850,United Kingdom,20.34,2010-12-01
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850,United Kingdom,22.00,2010-12-01
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850,United Kingdom,20.34,2010-12-01
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850,United Kingdom,20.34,2010-12-01
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,7.65,17850,United Kingdom,15.30,2010-12-01

In [14]:
cust_prod = trans_df[['product_id', 'cust_id']]

In [15]:
cust_prod.head(6)

  product_id  cust_id
0     85123A    17850
1      71053    17850
2     84406B    17850
3     84029G    17850
4     84029E    17850
5      22752    17850

In [24]:
products_uniq = pd.DataFrame(trans_df.product_id.unique())

In [25]:
products_uniq.head(6)

        0
0  85123A
1   71053
2  84406B
3  84029G
4  84029E
5   22752

In [26]:
products_uniq.rename(columns={0:'product'}, inplace = True)

In [27]:
products_uniq['product'] = products_uniq['product'].astype('category')

In [28]:
products_uniq['code'] = products_uniq['product'].cat.codes

In [29]:
products_uniq.head(6)

  product  code
0  85123A  3249
1   71053  2649
2  84406B  2855
3  84029G  2803
4  84029E  2802
5   22752  1605

In [30]:
product_map = products_uniq.set_index('code')['product'].to_dict()

In [45]:
product_map[0]

'10002'

In [35]:
users_unique = pd.DataFrame(trans_df.cust_id.unique())

In [36]:
users_unique.head(6)

       0
0  17850
1  13047
2  12583
3  13748
4  15100
5  15882

In [37]:
users_unique.rename(columns={0:'cust_id'}, inplace=True)

In [38]:
users_unique['cust_id'] = users_unique['cust_id'].astype('category')

In [39]:
users_unique['code'] = users_unique['cust_id'].cat.codes

In [40]:
users_unique.head(6)

  cust_id  code
0   17850  4048
1   13047   540
2   12583   191
3   13748  1047
4   15100  2029
5   15882  2621

In [41]:
users_map = users_unique.set_index('code')['cust_id'].to_dict()

In [44]:
users_map

{0: 12346,
 1: 12347,
 2: 12348,
 3: 12349,
 4: 12350,
 5: 12352,
 6: 12353,
 7: 12354,
 8: 12355,
 9: 12356,
 10: 12357,
 11: 12358,
 12: 12359,
 13: 12360,
 14: 12361,
 15: 12362,
 16: 12363,
 17: 12364,
 18: 12365,
 19: 12367,
 20: 12370,
 21: 12371,
 22: 12372,
 23: 12373,
 24: 12374,
 25: 12375,
 26: 12377,
 27: 12378,
 28: 12379,
 29: 12380,
 30: 12381,
 31: 12383,
 32: 12384,
 33: 12386,
 34: 12388,
 35: 12390,
 36: 12391,
 37: 12393,
 38: 12394,
 39: 12395,
 40: 12397,
 41: 12398,
 42: 12399,
 43: 12401,
 44: 12402,
 45: 12403,
 46: 12405,
 47: 12406,
 48: 12407,
 49: 12408,
 50: 12409,
 51: 12410,
 52: 12412,
 53: 12413,
 54: 12414,
 55: 12415,
 56: 12417,
 57: 12418,
 58: 12420,
 59: 12421,
 60: 12422,
 61: 12423,
 62: 12424,
 63: 12425,
 64: 12426,
 65: 12427,
 66: 12428,
 67: 12429,
 68: 12430,
 69: 12431,
 70: 12432,
 71: 12433,
 72: 12434,
 73: 12435,
 74: 12436,
 75: 12437,
 76: 12438,
 77: 12441,
 78: 12442,
 79: 12444,
 80: 12445,
 81: 12446,
 82: 12447,
 83: 12448,
 84: 12449,
 85: 12450,
 86: 12451,
 87: 12452,
 88: 12453,
 89: 12454,
 90: 12455,
 91: 12456,
 92: 12457,
 93: 12458,
 94: 12461,
 95: 12462,
 96: 12463,
 97: 12464,
 98: 12465,
 99: 12468,
 100: 12471,
 101: 12472,
 102: 12473,
 103: 12474,
 104: 12475,
 105: 12476,
 106: 12477,
 107: 12478,
 108: 12479,
 109: 12480,
 110: 12481,
 111: 12483,
 112: 12484,
 113: 12488,
 114: 12489,
 115: 12490,
 116: 12491,
 117: 12492,
 118: 12493,
 119: 12494,
 120: 12497,
 121: 12498,
 122: 12500,
 123: 12501,
 124: 12502,
 125: 12503,
 126: 12504,
 127: 12505,
 128: 12506,
 129: 12507,
 130: 12508,
 131: 12509,
 132: 12510,
 133: 12512,
 134: 12513,
 135: 12514,
 136: 12515,
 137: 12516,
 138: 12517,
 139: 12518,
 140: 12519,
 141: 12520,
 142: 12521,
 143: 12522,
 144: 12523,
 145: 12524,
 146: 12526,
 147: 12527,
 148: 12528,
 149: 12530,
 150: 12531,
 151: 12532,
 152: 12534,
 153: 12535,
 154: 12536,
 155: 12538,
 156: 12539,
 157: 12540,
 158: 12541,
 159: 12544,
 160: 12545,
 161: 12546,
 162: 12547,
 163: 12548,
 164: 12550,
 165: 12551,
 166: 12552,
 167: 12553,
 168: 12556,
 169: 12557,
 170: 12558,
 171: 12559,
 172: 12560,
 173: 12561,
 174: 12562,
 175: 12564,
 176: 12565,
 177: 12566,
 178: 12567,
 179: 12569,
 180: 12571,
 181: 12572,
 182: 12573,
 183: 12574,
 184: 12576,
 185: 12577,
 186: 12578,
 187: 12579,
 188: 12580,
 189: 12581,
 190: 12582,
 191: 12583,
 192: 12584,
 193: 12585,
 194: 12586,
 195: 12587,
 196: 12588,
 197: 12589,
 198: 12590,
 199: 12591,
 200: 12592,
 201: 12593,
 202: 12594,
 203: 12596,
 204: 12597,
 205: 12598,
 206: 12599,
 207: 12600,
 208: 12601,
 209: 12602,
 210: 12603,
 211: 12604,
 212: 12605,
 213: 12607,
 214: 12609,
 215: 12610,
 216: 12611,
 217: 12612,
 218: 12613,
 219: 12614,
 220: 12615,
 221: 12616,
 222: 12617,
 223: 12618,
 224: 12619,
 225: 12620,
 226: 12621,
 227: 12622,
 228: 12623,
 229: 12624,
 230: 12625,
 231: 12626,
 232: 12627,
 233: 12628,
 234: 12630,
 235: 12631,
 236: 12633,
 237: 12635,
 238: 12637,
 239: 12638,
 240: 12639,
 241: 12640,
 242: 12641,
 243: 12642,
 244: 12643,
 245: 12644,
 246: 12645,
 247: 12646,
 248: 12647,
 249: 12648,
 250: 12649,
 251: 12650,
 252: 12651,
 253: 12652,
 254: 12653,
 255: 12654,
 256: 12656,
 257: 12657,
 258: 12658,
 259: 12659,
 260: 12660,
 261: 12662,
 262: 12664,
 263: 12665,
 264: 12666,
 265: 12667,
 266: 12668,
 267: 12669,
 268: 12670,
 269: 12672,
 270: 12673,
 271: 12674,
 272: 12676,
 273: 12678,
 274: 12679,
 275: 12680,
 276: 12681,
 277: 12682,
 278: 12683,
 279: 12684,
 280: 12685,
 281: 12686,
 282: 12688,
 283: 12689,
 284: 12690,
 285: 12691,
 286: 12693,
 287: 12694,
 288: 12695,
 289: 12697,
 290: 12700,
 291: 12701,
 292: 12702,
 293: 12703,
 294: 12704,
 295: 12705,
 296: 12707,
 297: 12708,
 298: 12709,
 299: 12710,
 300: 12712,
 301: 12713,
 302: 12714,
 303: 12715,
 304: 12716,
 305: 12717,
 306: 12718,
 307: 12719,
 308: 12720,
 309: 12721,
 310: 12722,
 311: 12723,
 312: 12724,
 313: 12725,
 314: 12726,
 315: 12727,
 316: 12728,
 317: 12729,
 318: 12731,
 319: 12732,
 320: 12733,
 321: 12734,
 322: 12735,
 323: 12736,
 324: 12738,
 325: 12739,
 326: 12740,
 327: 12743,
 328: 12744,
 329: 12747,
 330: 12748,
 331: 12749,
 332: 12750,
 333: 12752,
 334: 12753,
 335: 12754,
 336: 12755,
 337: 12756,
 338: 12757,
 339: 12758,
 340: 12759,
 341: 12762,
 342: 12763,
 343: 12764,
 344: 12766,
 345: 12769,
 346: 12770,
 347: 12772,
 348: 12775,
 349: 12778,
 350: 12779,
 351: 12781,
 352: 12782,
 353: 12783,
 354: 12784,
 355: 12785,
 356: 12787,
 357: 12789,
 358: 12790,
 359: 12791,
 360: 12792,
 361: 12793,
 362: 12794,
 363: 12795,
 364: 12797,
 365: 12798,
 366: 12802,
 367: 12808,
 368: 12809,
 369: 12811,
 370: 12812,
 371: 12814,
 372: 12815,
 373: 12816,
 374: 12817,
 375: 12818,
 376: 12820,
 377: 12821,
 378: 12822,
 379: 12823,
 380: 12824,
 381: 12826,
 382: 12827,
 383: 12828,
 384: 12829,
 385: 12830,
 386: 12831,
 387: 12832,
 388: 12833,
 389: 12834,
 390: 12836,
 391: 12837,
 392: 12838,
 393: 12839,
 394: 12840,
 395: 12841,
 396: 12842,
 397: 12843,
 398: 12844,
 399: 12845,
 400: 12847,
 401: 12849,
 402: 12851,
 403: 12852,
 404: 12853,
 405: 12854,
 406: 12855,
 407: 12856,
 408: 12857,
 409: 12863,
 410: 12864,
 411: 12865,
 412: 12866,
 413: 12867,
 414: 12868,
 415: 12870,
 416: 12871,
 417: 12872,
 418: 12873,
 419: 12875,
 420: 12876,
 421: 12877,
 422: 12878,
 423: 12879,
 424: 12881,
 425: 12882,
 426: 12883,
 427: 12884,
 428: 12885,
 429: 12886,
 430: 12888,
 431: 12890,
 432: 12891,
 433: 12893,
 434: 12895,
 435: 12897,
 436: 12901,
 437: 12902,
 438: 12904,
 439: 12906,
 440: 12908,
 441: 12909,
 442: 12910,
 443: 12912,
 444: 12913,
 445: 12915,
 446: 12916,
 447: 12917,
 448: 12919,
 449: 12920,
 450: 12921,
 451: 12922,
 452: 12923,
 453: 12924,
 454: 12925,
 455: 12928,
 456: 12929,
 457: 12930,
 458: 12931,
 459: 12933,
 460: 12935,
 461: 12936,
 462: 12937,
 463: 12938,
 464: 12939,
 465: 12940,
 466: 12942,
 467: 12943,
 468: 12944,
 469: 12945,
 470: 12947,
 471: 12948,
 472: 12949,
 473: 12950,
 474: 12951,
 475: 12952,
 476: 12953,
 477: 12955,
 478: 12956,
 479: 12957,
 480: 12962,
 481: 12963,
 482: 12965,
 483: 12966,
 484: 12967,
 485: 12968,
 486: 12970,
 487: 12971,
 488: 12974,
 489: 12976,
 490: 12977,
 491: 12980,
 492: 12981,
 493: 12982,
 494: 12984,
 495: 12985,
 496: 12987,
 497: 12988,
 498: 12989,
 499: 12990,
 500: 12991,
 501: 12993,
 502: 12994,
 503: 12995,
 504: 12997,
 505: 12999,
 506: 13000,
 507: 13001,
 508: 13002,
 509: 13003,
 510: 13004,
 511: 13005,
 512: 13006,
 513: 13008,
 514: 13011,
 515: 13012,
 516: 13013,
 517: 13014,
 518: 13015,
 519: 13016,
 520: 13017,
 521: 13018,
 522: 13021,
 523: 13023,
 524: 13026,
 525: 13027,
 526: 13028,
 527: 13029,
 528: 13030,
 529: 13032,
 530: 13033,
 531: 13034,
 532: 13035,
 533: 13037,
 534: 13038,
 535: 13040,
 536: 13043,
 537: 13044,
 538: 13045,
 539: 13046,
 540: 13047,
 541: 13048,
 542: 13049,
 543: 13050,
 544: 13052,
 545: 13055,
 546: 13058,
 547: 13059,
 548: 13060,
 549: 13061,
 550: 13062,
 551: 13064,
 552: 13065,
 553: 13066,
 554: 13067,
 555: 13068,
 556: 13069,
 557: 13070,
 558: 13072,
 559: 13075,
 560: 13077,
 561: 13078,
 562: 13079,
 563: 13080,
 564: 13081,
 565: 13082,
 566: 13083,
 567: 13085,
 568: 13089,
 569: 13090,
 570: 13091,
 571: 13092,
 572: 13093,
 573: 13094,
 574: 13095,
 575: 13097,
 576: 13098,
 577: 13099,
 578: 13101,
 579: 13102,
 580: 13103,
 581: 13104,
 582: 13106,
 583: 13107,
 584: 13108,
 585: 13109,
 586: 13110,
 587: 13113,
 588: 13115,
 589: 13116,
 590: 13117,
 591: 13118,
 592: 13120,
 593: 13121,
 594: 13122,
 595: 13124,
 596: 13126,
 597: 13127,
 598: 13130,
 599: 13131,
 600: 13132,
 601: 13133,
 602: 13134,
 603: 13135,
 604: 13136,
 605: 13137,
 606: 13138,
 607: 13139,
 608: 13140,
 609: 13141,
 610: 13142,
 611: 13144,
 612: 13145,
 613: 13146,
 614: 13147,
 615: 13148,
 616: 13149,
 617: 13151,
 618: 13153,
 619: 13154,
 620: 13155,
 621: 13157,
 622: 13158,
 623: 13159,
 624: 13160,
 625: 13161,
 626: 13162,
 627: 13165,
 628: 13166,
 629: 13167,
 630: 13168,
 631: 13169,
 632: 13170,
 633: 13171,
 634: 13173,
 635: 13174,
 636: 13176,
 637: 13177,
 638: 13178,
 639: 13182,
 640: 13183,
 641: 13184,
 642: 13185,
 643: 13186,
 644: 13187,
 645: 13188,
 646: 13189,
 647: 13192,
 648: 13193,
 649: 13194,
 650: 13196,
 651: 13198,
 652: 13199,
 653: 13200,
 654: 13203,
 655: 13207,
 656: 13208,
 657: 13209,
 658: 13210,
 659: 13211,
 660: 13212,
 661: 13213,
 662: 13216,
 663: 13217,
 664: 13218,
 665: 13220,
 666: 13221,
 667: 13223,
 668: 13224,
 669: 13225,
 670: 13226,
 671: 13227,
 672: 13228,
 673: 13229,
 674: 13230,
 675: 13232,
 676: 13233,
 677: 13235,
 678: 13236,
 679: 13238,
 680: 13239,
 681: 13240,
 682: 13242,
 683: 13243,
 684: 13244,
 685: 13245,
 686: 13246,
 687: 13247,
 688: 13248,
 689: 13249,
 690: 13253,
 691: 13255,
 692: 13256,
 693: 13258,
 694: 13259,
 695: 13260,
 696: 13261,
 697: 13262,
 698: 13263,
 699: 13265,
 700: 13266,
 701: 13267,
 702: 13268,
 703: 13269,
 704: 13270,
 705: 13271,
 706: 13272,
 707: 13273,
 708: 13276,
 709: 13277,
 710: 13278,
 711: 13279,
 712: 13280,
 713: 13282,
 714: 13283,
 715: 13284,
 716: 13285,
 717: 13291,
 718: 13292,
 719: 13294,
 720: 13295,
 721: 13296,
 722: 13297,
 723: 13298,
 724: 13299,
 725: 13300,
 726: 13301,
 727: 13302,
 728: 13304,
 729: 13305,
 730: 13307,
 731: 13308,
 732: 13309,
 733: 13310,
 734: 13311,
 735: 13313,
 736: 13314,
 737: 13316,
 738: 13317,
 739: 13318,
 740: 13319,
 741: 13320,
 742: 13321,
 743: 13322,
 744: 13323,
 745: 13324,
 746: 13325,
 747: 13327,
 748: 13328,
 749: 13329,
 750: 13330,
 751: 13332,
 752: 13334,
 753: 13336,
 754: 13338,
 755: 13339,
 756: 13340,
 757: 13341,
 758: 13343,
 759: 13344,
 760: 13345,
 761: 13347,
 762: 13348,
 763: 13349,
 764: 13350,
 765: 13351,
 766: 13352,
 767: 13354,
 768: 13355,
 769: 13356,
 770: 13357,
 771: 13358,
 772: 13359,
 773: 13362,
 774: 13363,
 775: 13364,
 776: 13365,
 777: 13366,
 778: 13368,
 779: 13369,
 780: 13370,
 781: 13372,
 782: 13373,
 783: 13375,
 784: 13376,
 785: 13379,
 786: 13381,
 787: 13382,
 788: 13384,
 789: 13385,
 790: 13388,
 791: 13389,
 792: 13390,
 793: 13391,
 794: 13394,
 795: 13395,
 796: 13396,
 797: 13397,
 798: 13398,
 799: 13402,
 800: 13403,
 801: 13404,
 802: 13405,
 803: 13408,
 804: 13410,
 805: 13411,
 806: 13414,
 807: 13416,
 808: 13417,
 809: 13418,
 810: 13419,
 811: 13420,
 812: 13421,
 813: 13422,
 814: 13425,
 815: 13426,
 816: 13427,
 817: 13428,
 818: 13429,
 819: 13430,
 820: 13431,
 821: 13434,
 822: 13435,
 823: 13436,
 824: 13437,
 825: 13439,
 826: 13441,
 827: 13447,
 828: 13448,
 829: 13449,
 830: 13450,
 831: 13451,
 832: 13452,
 833: 13453,
 834: 13455,
 835: 13456,
 836: 13458,
 837: 13460,
 838: 13461,
 839: 13462,
 840: 13464,
 841: 13466,
 842: 13467,
 843: 13468,
 844: 13470,
 845: 13471,
 846: 13473,
 847: 13474,
 848: 13475,
 849: 13476,
 850: 13477,
 851: 13479,
 852: 13481,
 853: 13482,
 854: 13483,
 855: 13484,
 856: 13485,
 857: 13486,
 858: 13487,
 859: 13488,
 860: 13489,
 861: 13491,
 862: 13492,
 863: 13493,
 864: 13494,
 865: 13495,
 866: 13496,
 867: 13497,
 868: 13499,
 869: 13500,
 870: 13501,
 871: 13502,
 872: 13503,
 873: 13504,
 874: 13505,
 875: 13506,
 876: 13507,
 877: 13508,
 878: 13509,
 879: 13510,
 880: 13512,
 881: 13513,
 882: 13514,
 883: 13515,
 884: 13516,
 885: 13517,
 886: 13518,
 887: 13519,
 888: 13520,
 889: 13521,
 890: 13522,
 891: 13523,
 892: 13524,
 893: 13525,
 894: 13527,
 895: 13529,
 896: 13531,
 897: 13532,
 898: 13533,
 899: 13534,
 900: 13536,
 901: 13538,
 902: 13539,
 903: 13544,
 904: 13546,
 905: 13548,
 906: 13549,
 907: 13551,
 908: 13552,
 909: 13555,
 910: 13557,
 911: 13558,
 912: 13560,
 913: 13561,
 914: 13562,
 915: 13563,
 916: 13564,
 917: 13565,
 918: 13566,
 919: 13568,
 920: 13569,
 921: 13570,
 922: 13571,
 923: 13572,
 924: 13573,
 925: 13575,
 926: 13576,
 927: 13577,
 928: 13579,
 929: 13581,
 930: 13583,
 931: 13584,
 932: 13587,
 933: 13588,
 934: 13589,
 935: 13590,
 936: 13591,
 937: 13592,
 938: 13593,
 939: 13594,
 940: 13596,
 941: 13598,
 942: 13599,
 943: 13600,
 944: 13601,
 945: 13602,
 946: 13603,
 947: 13606,
 948: 13607,
 949: 13610,
 950: 13611,
 951: 13614,
 952: 13615,
 953: 13617,
 954: 13618,
 955: 13621,
 956: 13623,
 957: 13626,
 958: 13627,
 959: 13629,
 960: 13630,
 961: 13631,
 962: 13632,
 963: 13634,
 964: 13635,
 965: 13636,
 966: 13637,
 967: 13638,
 968: 13639,
 969: 13642,
 970: 13643,
 971: 13644,
 972: 13645,
 973: 13647,
 974: 13649,
 975: 13650,
 976: 13651,
 977: 13652,
 978: 13654,
 979: 13655,
 980: 13656,
 981: 13657,
 982: 13658,
 983: 13659,
 984: 13662,
 985: 13663,
 986: 13666,
 987: 13667,
 988: 13668,
 989: 13669,
 990: 13670,
 991: 13672,
 992: 13673,
 993: 13675,
 994: 13678,
 995: 13680,
 996: 13681,
 997: 13682,
 998: 13684,
 999: 13685,
 ...}